apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # echo -n 'rootpassword' | base64
  MYSQL_USER: d29yZHByZXNz  # echo -n 'wordpress' | base64
  MYSQL_PASSWORD: d29yZHByZXNzcGFzcw==  # echo -n 'wordpresspass' | base64