services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  backend:
    build: ./back
    environment:
      db_host: db
      db_port: 5432
      db_name: mydatabase
      db_user: postgres
      db_password: password
    depends_on:
      - db
    networks:
      - app-network
  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    networks:
    - app-network
  frontend:
    build: .
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge