apiVersion: v1
kind: Pod
metadata:
  name: python-time-pod
spec:
  containers:
  - name: python-container
    image: python:3.9
    command: ["bash", "-c", "while true; do python -c 'import time; print(time.ctime()); time.sleep(10)'; done"]
